### ISSUE TITLE
Limit Ravencoin Node upload speed via command

### ISSUE THREAD

**Issue by espy1** [RavenProject/Ravencoin#1091]
### Describe the issue
Please add a way to limit upload bandwidth within node instead of total bandwidth used per day.
Sort of how torrents upload can be limited.
Thank you.

**Comment by TronBlack** [comment]
Bandwidth is an amount of data per unit time.  And the config is per node. 

Maybe if you could include a reason, or what isn’t possible using the current capability, there might be a better solution that already exists.

**Comment by espy1** [comment]
My understanding is currently bandwidth is limited via total usage over 24 hour period.

For example - If the limit is set for 100 MB it would stop acting as a node until it resets but until the cap is hit can use max bandwidth.

I'd like to set a cap on max upload bandwidth allowed of X mbps or x kbps. This would prevent the whole pipe from being used. Maybe more people would run nodes if they could limit max upload speed allowed.

![image](https://user-images.githubusercontent.com/88622677/128636482-0c3f37e9-9d12-422c-9778-02f2e40f8023.png)

**Comment by lsji07** [comment]
Reduce Traffic

By default, Ravencoin Core allows up to 125 connections to different peers, 8 of which are outbound. You can therefore generally have a high limit of  117 inbound connections.

The default settings can result in relatively significant traffic consumption.

Ways to reduce traffic:

Maximum Upload Targets
-maxuploadtarget=<MB per day>
A major component of the traffic is caused by serving historic blocks to other nodes during the initial blocks download phase (syncing up a new node). This option can be specified in MB per day and is turned off by default. This is not a hard limit; only a threshold to minimize the outbound traffic. When the limit is about to be reached, the uploaded data is cut by no longer serving historic blocks (blocks older than one week). Keep in mind that new nodes require other nodes that are willing to serve historic blocks. The recommended minimum is 1440 blocks per day (max. circa 2880MB per day with 100% full blocks). Note that currently the blocks are not full and this figure can be substantially reduced.

Disable listening
-listen=0
Disabling listening will result in fewer nodes connected (remember the maximum of 8 outbound peers). Fewer nodes will result in less traffic usage as you are relaying blocks and transactions to fewer nodes.

Reduce maximum connections
-maxconnections=<num>
Reducing the maximum connected nodes to a minimum could be desirable if traffic limits are tiny. Keep in mind that Ravencoin's trustless model (the same as Bitcoin's) works best if you are connected to a handful of nodes.

Blocks-only mode
-blocksonly
Causes your node to stop requesting and relaying transactions unless they are part of a block and also disables listening as described above.

This reduces your node’s bandwidth to the absolute minimum necessary to stay synchronized with the network, about 3 GB incoming data per day and about 1 megabyte of outgoing data per day with the network under full load. The network is currently lightly loaded and data should be minimal. It does mean that your node won’t see incoming transactions until they’ve received at least one confirmation. Note that several functions of the ravencoin network for restricted assets specifically require monitoring the mempool (made up of transactions not yet added to a block) These features likely will not function in blocks only mode. 

You will still be able to send other transactions from the built-in wallet or from peers you’ve whitelisted using the -whitelist parameter.

The above information is purely to assist those on restricted or metered internet connections until someone funds or develops the code required to add the bandwidth limiting required. I have reservations about implementing bandwidth limitation as a feature to the ravencoin core wallet as this may introduce additional unintended issues if implemented with future undesirable bandwidth limiting on most nodes when the network is in a period of significant growth.

I am of the opinion that while the network is young and growing as many nodes as possible should, by default, be secure as a priority and also be configurable to become full nodes by informed users. The core wallet is compliant with those objectives.

Ravencoin's network ideally needs users and node operators to share as much data as possible to keep the network ledger of data current, operational, decentralised and secure. Run those full nodes wherever possible!

**Comment by GrumpyGiuseppe** [comment]
I limited my node to 30 mbit/s upload with NetLimiter.
Works flawless.
But I already got a copy of NetLimiter Pro.
As far as I know the free version will also work out fine.

**Comment by espy1** [comment]
> 
> 
> I limited my node to 30 mbit/s upload with NetLimiter.
> Works flawless.
> But I already got a copy of NetLimiter Pro.
> As far as I know the free version will also work out fine.

I run this in Docker on my NAS - this wouldn't be an option.
