### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by BrightXiaoHan** [RavenProject/Ravencoin#1238]

**Comment by Preserved2** [comment]
not necessarily. If you have ideas to work on it and expand it then it is
not dead. Ravencoin was never a scam coin get rich quick scheme. It was
purpose built for things like tokenization that could support NFTS, digital
copyright, physical property and such like. A lot of NFTs were scams or
just failed - but that doesn't mean the protocol changes Ravencoin
introduced are worthless.

The beauty of Ravencoin is that it doesn't rely on smart contracts which -
if poorly (or deliberately poorly) written could cost people a lot of money.

That was and is the purpose. As long as people want what Ravencoin has to
offer it isn't gonna be dead. If you're going by price per token alone
then... yeah it's not looking great right now, but who knows. I have some
RVN. I didn't acquire it to speculate that it would be 10k per RVN one day.
(would be nice) but it's not being widely adopted. tZero wallet went out of
business and Coinbase won't list it so there are limited options for
acquiring or trading RVN.

More work has been put into Ravencoin that was ever put into Doge and
20,000 or so other crypto projects. Literally when Musk promoted doge and
said he'd have engineers work on it and he 1000x the price, some people did
a handful of undeployed checkins and then they stopped working on Doge,
Meanwhile RVN had continuous work put into it. Doge is garbage, even with
the biggest scam artist in the world promoting it it's sits at 7 cents.
Look at the github for Doge - compare it with the github for Ravencoin. I'm
sure the checkins have slowed for RVN, but worthless doge didn't have a
checkin or pull request for 3 years before Musk talked about it, then it
had 6 months of meaningless pull requests that were never merged and Musk
pumped and dumped Doge.... RVN is real. To your main point I hope the
project succeeds because over the past few years horrible smart contracts
have gotten people robbed. RVN doesn't use smart contracts.

Every token project that has come along floated around from pennies to
dollars and no engineers were actually working on those projects. Ravencoin
was and is a true project. Whether the public picks up on that or not I
don't know.

**Comment by corviato1** [comment]
It is not

**Comment by Preserved2** [comment]
If coinbase would list it then you wouldn't ask the question. Coinbase
lists pure crap and may go out of business in the coming months. There is
no more project worth of being listed at a major exchange than Ravencoin -
but I think Coinbase and Gemini are done for in the US and as far as making
money from RVN - making money off holding a coin is not the only value it
has. Coinbase is going under, they've been caught too many times leaking
announcements of shitcoins they were going to sell all the way back to the
2017 Bitcoin Cash debachle. True believes in RVN wanted it to be listed and
did everything they could do - but Coinbase is not going to list real value
- just shitcoins.

**Comment by Preserved2** [comment]
I"ve used github and such for years - I didn't realize some of the
checkins are just people's questions and opinions. RVN forever ELON MUSK
never.
