### ISSUE TITLE
ravencoin.network 503 error

### ISSUE THREAD

**Issue by tureck1y** [RavenProject/Ravencoin#1239]
ravencoin.network return 503 error "Service Temporarily Unavailable"

**Comment by jeroz1** [comment]
I reached out to my contact person asking what their plans are

**Comment by dicklarsson** [comment]
The website is updated with new Block explorer links.

**Comment by corviato1** [comment]
This issue is with ravencoin.network, not the codebase.
As of today, there is still an issue.

Going to close as this issue does not fall within this Github repository (RavenProject/Ravencoin).

![ravencoin-network-error](https://github.com/RavenProject/Ravencoin/assets/44780076/9ab91401-0fb6-45cb-8173-a5ed93433cd5)
