### ISSUE TITLE
BDB 5.3 namespace clash breaks build

### ISSUE THREAD

**Issue by jyap808** [RavenProject/Ravencoin#193]
### Describe the issue

Building using ```--with-incompatible-bdb``` and BDB 5.3 fails.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:

1. Install: ```libdb5.3++ libdb5.3++-dev libdb5.3-dev```
2. Configure with flag ```--with-incompatible-bdb```:
```./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC" --with-incompatible-bdb```
3. Run make

Error:
```In file included from /usr/include/db_cxx.h:64:0,
                 from ./wallet/db.h:22,
                 from ./wallet/walletdb.h:12,
                 from wallet/wallet.h:20,
                 from miner.cpp:31:
/usr/include/db.h:151:44: error: 'typedef struct __channel CHANNEL' redeclared as different kind of symbol
 struct __channel; typedef struct __channel CHANNEL;
                                            ^
In file included from coins.h:22:0,
                 from txmempool.h:20,
                 from miner.h:11,
                 from miner.cpp:7:
./assets/assets.h:58:5: note: previous declaration 'AssetType CHANNEL'
     CHANNEL,
     ^
In file included from /usr/include/db_cxx.h:64:0,
                 from ./wallet/db.h:22,
                 from ./wallet/walletdb.h:12,
                 from wallet/wallet.h:20,
                 from miner.cpp:31:
/usr/include/db.h:2695:2: error: 'CHANNEL' does not name a type
  CHANNEL *channel; /* Pointer to internal state details. */
  ^
Makefile:6361: recipe for target 'libraven_server_a-miner.o' failed
```

### Expected behaviour

Should build fine.

### Actual behaviour

Build fails

### Machine specs:

- OS: Ubuntu 16 LTS

**Comment by underdarkskies** [comment]
The reason bitcoin and Ravencoin have settled on using BDB 4.8 is because the wallet.dat files will be universally accepted by multiple versions of the client. 
Both Bitcoin and Ravencoin releases are compiled with bdb 4.8.
Source: https://github.com/bitcoin/bitcoin/blob/master/depends/packages/bdb.mk

 If 4.8 is an option for your use case, I would highly recommend compiling Ravencoin with bdb 4.8 not any other version, so that you wallet.dat remains compatible with future releases. 

If you are interested in compiling ravencoin as a static self contained executable for linux, or any other platform, I have written a Static build compile guide.

This can be found here: https://github.com/underdarkskies/Ravencoin/tree/build-docs/static-builds

Only if BDB 5.3 is absolutely required for your environment would I consider compiling Ravencoin (or bitcoin ) with it, and it may produce certain undesirable issues, firstly wallet.dat incompatibility, as well as the potential for segfaults.

**Comment by underdarkskies** [comment]
Two other issues...
Ubuntu 18 Bionic is the preferred build platform for production wallets, as the GCC compiler bundled in Ubuntu 16.04 is known to be buggy.

If you are deadset on compiling Ravencoin with an alternate version of BDB such as 5.3, you cannot compile it with the prebuilt release included from apt install. you must follow these steps:
```
$ cd ~/ravencoin
$ wget http://download.oracle.com/berkeley-db/db-5.3.28.NC.tar.gz
$ echo '76a25560d9e52a198d37a31440fd07632b5f1f8f9f2b6d5438f4bc3e7c9013ef  db-5.3.28.NC.tar.gz' | sha256sum -c
The last command should return a value of db-5.3.28.NC.tar.gz: OK.

Next, unpack the BerkeleyDB source and compile.

$ tar -xvf db-5.3.28.NC.tar.gz
$ cd db-5.3.28.NC/build_unix
$ mkdir -p build
$ BDB_PREFIX=$(pwd)/build
$ cd ~/ravencoin 
$ ./autogen.sh
$ ./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC" --with-incompatible-bdb
$ make install
```
HOWEVER I CAUTION HIGHLY AGAINST BUILDING RAVENCOIN WITH ANY OTHER VERSION OF BDB and Ubuntu 18 (bionic) should be the most reliable build platform, in fact it is required for static builds.

**Comment by underdarkskies** [comment]
Ok, so enough of the history lesson. LOL! I'm sure you don't need it. I can see whats going on now with BDB5.3
db.h  defines:

`struct __channel;	typedef struct __channel CHANNEL;`

and so does 
assets.h as:
```
enum AssetType
{
    ROOT,
    OWNER,
    SUB,
    UNIQUE,
    CHANNEL,
    VOTE,
    INVALID
};
```

I guess BDB 4.8 does not define CHANNEL  so the issue has not come up before since 4.8 is the general build. Until Core renames the AssetType CHANNEL to something else, i do not think ravencoin supports BDB 5.3  Good Catch!! +1
