### ISSUE TITLE
feature request - asset control

### ISSUE THREAD

**Issue by Bayminer007** [RavenProject/Ravencoin#211]
Allow core wallet users to burn asset tokens out of their wallet.  This will allow users to permanently eliminate unwanted spam tokens, including those with names or metadata IPFS hashes that they do not wish to have associated with their RVN address.

**Comment by bedri** [comment]
I edit my previous comment to make some corrections on the logic and fix some typos.

**Comment by blondfrogs** [comment]
@bedri You might want to be create your own issue with your comment in it. I want to make sure that we don't lose your thoughts on assets transfer

**Comment by bedri** [comment]
@blondfrogs Yes sure. Thanks for guiding.

**Comment by bedri** [comment]
About the IPFS hashes being seen on the blockchain, I will suggest to sign the hashes recipient's pub key so that while senders of the asset still having the clear IPFS hash, the recipients will get the hash encrypt with  their public key so easily decrypt the encrypted hash and get the clear IPFS hash. Even if the unwanted/spam asset transaction enters the blockchain IPFS hash of the unwanted content will be shown encrypted in the explorer so a degree of privacy and a way of escape from false accusations will get satisfied.
I can open a seperate issue for this idea as well if requested.
