### ISSUE TITLE
error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by benyanke** [RavenProject/Ravencoin#25]
Upon running any of the files for ubuntu on ubuntu...I get this.

Tried on both ubuntu mate and ubuntu server, 16.04.

**Comment by Brock-Wood** [comment]
Did you follow the instructions? https://github.com/RavenProject/Ravencoin/blob/master/binaries/release/linux/README.md

**Comment by jduncan8142** [comment]
I"m receiving the same error in running raven-qt. All dependencies installed per the instructions. Running Linux Mint 18.3. Error: ./raven-qt: error while loading shared libraries: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory

So I almost solved this. Here is what I did:

1. Create links to missing files. 
`sudo ln /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.62.0`
`sudo ln /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0 /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.62.0`
`sudo ln /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.62.0`
`sudo ln /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0 /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.62.0`

2. Upgrade libstdc
Try: 
`sudo apt-get install libstdc++6`
if that doesn't work do this:
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade`

3. Then install Qt5.7
`wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run`
`chmod +x qt-opensource-linux-x64-5.7.0.run`
`./qt-opensource-linux-x64-5.7.0.run`

4. Now I'm getting this:
`./raven-qt: symbol lookup error: ./raven-qt: undefined symbol: _ZN6google8protobuf8internal14WireFormatLite16VerifyUtf8StringEPKciNS2_9OperationES4_
`
Haven't found a fix for this yet.

**Comment by bedri** [comment]
Your system has libboost 1.62 but the binary version of Ravencoin daemon or qt executable looks for 1.58.
The solution to your problem is to compile the Ravencoin from sourcecode (that's what I did and make it work).
Make sure that you follow all the compiling instructions from the github repository. After installation of the requirements,
> git clone https://github.com/RavenProject/Ravencoin.git
> cd Ravencoin
> ./autogen.sh
> ./configure --enable-cxx --disable-shared --with-pic CXXFLAGS="-fPIC -O" CPPFLAGS="-fPIC -O"
> make
> make install (this is optional)
configure parameters are for to prevent [-fPIC compile issue](https://github.com/RavenProject/Ravencoin/issues/27)

src/ravend
src/raven-cli
src/raven-tx
src/qt/raven-qt

These will be your raven executables. If you want to use Qt version (GUI version) run src/qt/raven-qt from either commandline or from folder view of Ubuntu. The above 4 executable binaries locations are relative to Ravencoin directory that you created in the 
> git clone https://github.com/RavenProject/Ravencoin.git
command.

Hope this helps. Good luck.

**Comment by jacksonpchen** [comment]
If your question has been answered, please close this issue.
