### ISSUE TITLE
Can't sync the blockchain with ravend

### ISSUE THREAD

**Issue by fedsten** [RavenProject/Ravencoin#254]
I tried to launch ravend on an Ubuntu18.04 machine, and after installing I successfully started the server with `ravend -daemon` .
Then, I tried with raven-cli some basic commands which seemed to work (e.g. getnewaddress), but I realized that I couldn't see any incoming transaction and I noticed the block count was still 0. After about an hour the blockchain still hasn't started syncing, I tried both with mainnet and testnet.
On the same machine I am simultaneously running a synced Bitcoin node, so it shouldn't be a networking issue. 

Any idea what could be the source of the problem?

**Comment by russkidooski** [comment]
try putting this in your raven.conf
`addnode=104.238.146.167:8767
addnode=165.227.216.124:8767
addnode=104.238.146.167:8767
addnode=85.186.205.190:8767
addnode=80.222.148.243:8767
addnode=34.250.168.91:8767
addnode=72.205.213.251:8767`

**Comment by russkidooski** [comment]
also try `getpeerinfo` to list peers you are connected to

**Comment by WoundedxWarr1or** [comment]
Salutations,  The Wallet was working perfectly for over a month, and then for an undetermined reason it failed to sync.  When I restart the wallet it will go to aprox. 15% and just stop.  I would really like to recover the 733 coins that remained in the wallet, to balance out the power I burned up mining these coins and supporting the network.  Instead of providing a myriad of useless detail(s), pls tell me what information you require to assist.  

Please advise .. thank you.

Very Respectfully,
WX2

Addendum:  I did run the backup module; but I guess that I am not smart enough to apply to correct syntax in the command line to get it to stick.

**Comment by underdarkskies** [comment]
@WoundedxWarr1or create a separate issue please.

**Comment by WoundedxWarr1or** [comment]
Roger that .. Apologies.

**Comment by WoundedxWarr1or** [comment]
I came back to clean up my pony tail of your issue: and noticed my issue was similar to yours.  

I resolved the issue by nuking every file in the "chainstate" folder and copied and moved "wallet.dat out to a bin folder.  Re-open wallet and it will completely re-scan and once it completes syncing; close and move wallet.dat back and open again.  

I also had a struck transaction in the mempool.  After I completed a re-scan in the debug window under the network tab;  I typed in "listaddressgroupings" and the transaction completed.  

Hope this helps.

**Comment by blondfrogs** [comment]
@fedsten Is this issue resolved?

**Comment by fedsten** [comment]
Yes, the problem was due to an incorrect installation. Now I installed it again and is working correctly.

**Comment by blondfrogs** [comment]
Closing Issue
