### ISSUE TITLE
Halving

### ISSUE THREAD

**Issue by jmh77777** [RavenProject/Ravencoin#3]
Since this is a fork of Bitcoin with a bigger block reward size, does if half at the same rate?

Bitcoin halved at 210,000 blocks. Is it the same for this? Or since the reward is on a multiplier of 100, is halving on a multiplier of 10 or something? Perhaps 2,100,000 blocks?

**Comment by Larceniii** [comment]
I think others would like to know too and since this is top post on Google I looked at the code and found the answer.

In Ravencoin's /src/chainparams.cpp Around line **#120** we have:
`consensus.nSubsidyHalvingInterval = 2100000;  //~ 4 yrs at 1 min block time`

vs Bitcoin's /src/chainparams.cpp Around line **#77** we have:
`consensus.nSubsidyHalvingInterval = 210000; `

Which means that Ravencoin because has 10 times faster blocks (@1min each), it therefore has 10 times the number of blocks until reward halving _which means_ it's about the same amount of time between halvings. 4 years.

The Ravencoin devs even left a nice little comment in the code, thanks guys, nice touch.
