### ISSUE TITLE
ERROR PARSING JSON on Passphrase

### ISSUE THREAD

**Issue by Eranthea** [RavenProject/Ravencoin#40]
### Describe the issue
When i have encrypted my wallet i chose a long passphrase made from many words divided by space like "word1 word2 word3 word4" now walletnot recognize my passphrase and if i use console for unlock the wallet, when i input passphrase give me ERROR PARSING JSON"word2"
 pratically give error on first SPACE that divide first word
Now is impossible to use my RVN and is impossible to get the privatekey becouse the passphrase is not recognized
#### If so, please list the steps to reproduce below:
1. encrypt a wallet
2. chose a passphrase like "word1 word2 word3 word4" divided from space
3.

### Actual behaviour
from that moment if i try to send money give me Passphrase error
If i try to unlock wallet in console and i input the passphrase gime the error
ERROR PARSING JSON:"word2"
Pratically give an error in first space that divide word1 from word2

### What version of bitcoin-core are you using?
Raven Core versione v0.15.99.0-g8900994 (64-bit)

### Machine specs:
- OS: windows in different version (i test on diffetent pc)
- CPU: i7
- RAM: 32 
- Disk size: 2tr
- Disk Type (HD/SDD): hd

**Comment by bedri** [comment]
You can try in the console:
"word1\ word2\ word3\ word4\" 
by making sure that you embrace the passphrase by quotes and use backslash before the spaces as above. I am not sure if it will work but it worth a try.

**Comment by Eranthea** [comment]
Thank you for the advise, the issue is when i try to send RVN to another account, that ask me passphrase for send and give me back passphrase error... i will try in this way

**Comment by Eranthea** [comment]
I have try with word1\ word2\ word3\ word4 but do not work same
what you men with "
Correct JSON object format is something like:
{ "key1" : "value1" , "key2" : "value2" , "arrayKey1" : [ "element1" , "element2"] , "objectKey1" : { "elementObjectKey1" : "elementObjectValue1" , "elementObjectKey2" : "elementObjectValue2" } , "key3" , "value3" }

If the command line client does not need the passphrase to be embraced by quotes than your quotes are going into JSON object as { "passphrase" : ""word1 word2 word3 word4"" } and this breaks the JSON format. "
can you explin exaxtly how i can do? sorry im not so skilled in this

**Comment by bedri** [comment]
First backup your wallet.dat file in case something goes wrong.
Then from menu open Help->Debug window->Console(tab)
Type
walletpassphrase "word1 word2 word3 word4" 600
This command will unlock your wallet for 600 seconds
Then type
dumpprivkey <your_wallet_address>
your_wallet_address is your address that you accept payments. You should use the address that you have your coins in it.
Save this privatekey that you dumped to a secure place.

You can also use 
walletpassphrase "word1 word2 word3 word4" 600
command before sending your coins to another address.
If you give this command and send the coins to another unencrypted wallet than I guess you will get rid of this situation.

**Comment by bedri** [comment]
walletpassphrase "word1 word2 word3 word4" 600 works pretty fine for me in Linux wallet software. It should be caused by Window wallet software's or directly Windows' handling for the command. Other than you copy wallet.dat to a Linux machine and recover your coins, I think you the only way left is to wait for a fix. I am sure someone will look into this problem.

Before the methods in the article I mention below, can you lastly try the walletpassphrase command with single quotes as below?
walletpassphrase 'word1  word2 word3 word4' 600
This single quote should work. You can also try again escaping the double quotes and spaces both at the same time
walletpassphrase \"word1\  word2\ word3\ word4\" 600
and
walletpassphrase \"word1\  word2\  word3\  word4\" 600
(this last one have double spaces between \ and the w letter)
Other than these I am out of options since as I said it works on Linux wallet software without any error.

My windows laptop is crashing and I cannot test it on windows so I am sorry that I cannot help further. But I find [this](https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/) article that may help you while waiting for the fix of the problem. Maybe by try&error you can succeed with one of the methods given in the article.

**Comment by Eranthea** [comment]
No way, i test it all and give me of Passphrase incorrect or same json error
problem that i dont know how to use linux and i don know hot te test it, i do not have any linux machine
can you advise me a image file of some linux os that i can run from a pendrive? so i can make this test? i think is time for me for learn linux :)
thanks

**Comment by Eranthea** [comment]
I also findend this that look like exactly my issue, but i tried like explained here, but pywallet give me a setting error, i think i have done something wrong
https://github.com/nochowderforyou/clams/issues/306
maybe can help to better understand and guide me to solve, or solve the issue directly in next upgrade
thanks

**Comment by dkoppel** [comment]
Worked with this issue, pinned it down to the users password being different than they expected.  JSON errors are not from parsing the password but from the passphrase string being supplied incorrectly on the console.  Please close the issue, @Eranthea.  Thanks! I'm sorry I couldn't help you figure out your password.

**Comment by Eranthea** [comment]
thanks, so i think i lose my rvn :(
