### ISSUE TITLE
Mac network fails

### ISSUE THREAD

**Issue by BillWeld** [RavenProject/Ravencoin#41]
### Describe the issue
Log shows many error messages like

2018-03-02 12:48:55 connect() to [2001::4137:9e76:30ff:161a:f5ff:ffae]:8767 failed: No route to host (65)
2018-03-02 12:48:57 connect() to 67.207.45.43:8767 failed after select(): Connection refused (61)
2018-03-02 12:48:58 connect() to [2001::9d38:6ab8:45f:de76:d10d:f62b]:8767 failed: No route to host (65)

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Run the app.
2.
3.

### Expected behaviour
Not sure.  Fewer error messages and some indication of progress.

### Actual behaviour
Some peers, lots of activity but, apparently, no mining.

### What version of bitcoin-core are you using?
Raven Core version v0.15.99.0-6229502 (64-bit)
official binary

### Machine specs:
- OS:   macOS 10.13.3
- CPU:  Intel Core i7
- RAM:  16 GB
- Disk size:  500 GB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
[debug.log](https://github.com/RavenProject/Ravencoin/files/1775139/debug.log)

**Comment by jediwarpraptor** [comment]
Based on the `debug.log` attached, your node is processing and validating blocks as expected.  I'm pretty certain that the connect errors are benign and don't impact performance or functionality of your node. Essentially what's happening is that your Raven node is reaching out trying to make connections to other peer nodes but those nodes are not responding to external connections.  This could be for a number of legitimate reasons, most likely because those peers have blocked incoming connections via firewall rules.

The reason you aren't seeing any coins from mining is almost certainly because the network difficulty is so high at this point that your likelihood of finding a block doing solo-CPU mining is extremely low.
