### ISSUE TITLE
wallet.dat corrupt, salvage failed

### ISSUE THREAD

**Issue by wuwei200000** [RavenProject/Ravencoin#410]
。。。。。。。。 I have only one backup.。。。。。
HOW can i do? big thanks.!!!!

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。
E:\py>python pywallet.py --recover --write_text --recov_size 512Mio --coin_type
litecoin --recov_device e:wallet.dat --recov_outputdir e:\123
WARNING:root:pycrypto or libssl not found, decryption may be slow
Enter the passphrase for the wallet that will contain all the recovered keys:
Enter the passphrase for the wallet that will contain all the recovered keys:
### **WHAT KEYS？？？？？ my wallet have no password**

**Comment by fokep** [comment]
I'm sorry to hear you have issues with your wallet but this repository is unable to provide help with `pywallet.py`. You are welcome to join either one of the discord groups (see https://ravencoin.com/community/) where team members and community may be of assistance.

**Comment by bedri** [comment]
These kind of problems **really does not belong here**. I want to advice to seek the solution in bitcoin stackexchange (https://bitcoin.stackexchange.com/) website because Ravencoin is just a fork of Bitcoin and it preserves all kind of features that bitcoin serves for wallets.

Additionally:
1) If you encrypt your wallet and lose your password, it's your fault.
2) If you did not backup your wallet, it's your fault.
3) If you haven't read anything about bitcoin wallets, softwares, passwords, encryption or any related source of information for your safety and security of your OWN MONEY, again it's your fault. 

Here only the Protocol and Code changes, proposals, issues, bugs and all other kind of related subjects are discussed. This is not a call center to help customers. Please be careful about this and ask about your problems in the related mediums.
Thank you.

PS: Here is not the place to teach about coin's python script "HOW TO" class. So please follow the instructions above.

I suggest to close this issue. Thanks.

**Comment by blondfrogs** [comment]
Closing this issue, because this is the wrong place for it
