### ISSUE TITLE
Question: miner_tests.cpp with new data

### ISSUE THREAD

**Issue by cryptozeny** [RavenProject/Ravencoin#488]
Hi Raven Devs :smiley:

https://github.com/RavenProject/Ravencoin/blob/a01dd7b69722441a719468626af152dc68c5eaa5/src/test/miner_tests.cpp#L48

```cpp
            {3, 0x1147b7d},  {1, 0x115c9f0},  {6, 0x11c6644},  {1, 0x1377d45},
            {1, 0x1050f1c},  {6, 0x1092cdb},  {5, 0x1201fdf},  {4, 0x1081b87},
            {1, 0x10ecd8e},  {5, 0x1124186},  {2, 0x16556d5},  {1, 0x1445631},
            {4, 0x13b8cb3},  {6, 0x13bfe16},  {3, 0x154cec8},  {6, 0x11e277f},
```

I want to do `miner_tests` with new data. Could you tell me how to create new one? `blockinfo` If I can, I would like to reinforce the test data and contribute to the this project. :smile:

I tried a lot. But I could not get the `extranonce` :sob:

**Comment by spyder46n2** [comment]
Sorry so slow to respond...
In the same file (miner_tests.cpp) starting at line 345, there is a large block of code commented out.   That is the section of code that we used to generate the nonce that is currently used. It can take a very long time for them to be generated, I had a machine running for weeks to get all of the ones we are using. You should be able to put that section of code back in, compile, and just run the test. It has been nearly a year since I added all the nonce we needed for these tests...it won't surprise me if it is broken.  Let me know here if you run into a problem and I'll have a look-see.  I'll try to check-in on this issue now and again to see if you have any questions...

One other thing, I did make changes to what information is printed out while the tests are running.  If the test looks like it is running, but isn't outputting any nonce after a few hours, go look at the src/test/test_raven.cpp file, line 43, There is a comment there about making a change in the VerifyScript method to allow additional debug information to be displayed while running tests. I don't think this should be the case but I'm not 100% certain it won't.

**Comment by cryptozeny** [comment]
Thanks the answer. I will test it if I have a time soon...

**Comment by blondfrogs** [comment]
Closing as this isn't an issue
