### ISSUE TITLE
Segmentation fault caused by RPC for assets

### ISSUE THREAD

**Issue by volbil** [RavenProject/Ravencoin#595]
### Describe the issue
I'm currently working on alternative explorer and while making couple simultaneous requests to ```listassetbalancesbyaddress``` rpc method node goes down with ```Segmentation fault (core dumped)```. Same behaviour noticed using cli.

After some debugging I figured out that it's happening after calling ```FlushStateToDisk()``` function in [assetdb.cpp](https://github.com/RavenProject/Ravencoin/blob/master/src/assets/assetdb.cpp#L249) file. After going even deeper in rabbit hole I discovered that ```FlushStateToDisk()``` function faling at [this](https://github.com/RavenProject/Ravencoin/blob/master/src/validation.cpp#L2734-L2736) point.

### Can you reliably reproduce the issue?
Yes, it's happening each time when I'm making couple ```listassetbalancesbyaddress``` requests with small delay.

#### If so, please list the steps to reproduce below:
1. Launch daemon with assetindex enabled
2. Make couple simultaneous ```listassetbalancesbyaddress``` requests via rpc or cli
3. Node goes down with ```Segmentation fault (core dumped)``` error message

### Expected behaviour
Node return address asset balances without issues.

### Actual behaviour
Node goes down with ```Segmentation fault (core dumped)``` error message.

### Machine specs:
- OS: macOS Mojave 10.14.1
- CPU: Intel Core i7 2,2 GHz
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 256 GB
- Disk Type (HD/SDD): SSD

But same error happening on my Ubuntu instance, so it's not platform specific issue.

**Comment by volbil** [comment]
Apparently [this](https://github.com/RavenProject/Ravencoin/blob/master/src/validation.cpp#L2762-L2764) code should catch such errors but for some reason its not working 🤔

**Comment by ravenlandpush** [comment]
Interesting! I've on occasion had a few segmentation faults but I was often not able to recreate. Recently a similar issue SEGV was to do with the way I'd compiled my source, so if you have compiled from source, consider this as a potential cause.

I think a couple of other people like bokito had issues very similar to what your describing. As I understand it one way to potentially help with this is to use rabbitmq, or set the command queuing vars in .raven/raven.conf . 

The asset explorer scraper script Ravenland uses is sequential for the purpose of not overflowing the RPC queue. As I myself have noticed some instabilty when making large requests over 50k records..

My 2 cents, hope it helps in the meantime.

Best wishes,
Adam

**Comment by volbil** [comment]
Thanks for your reply @ravenlandpush !
Glad I'm not only one who across this issue :)

**Comment by TronBlack** [comment]
Was this duplicated with the binaries that we built?
If so, this should be fixed before this issue is closed.

**Comment by ravenlandpush** [comment]
No worries! hopefully it is something compile related. Did you use the ravencoin binaries provided, or compile yourself from source?

**Comment by volbil** [comment]
@TronBlack I havent tried (yet) official binaries, going to do this right now.
@ravenlandpush can you tell me more about `command queuing vars` you mentioned before?

**Comment by ravenlandpush** [comment]
Since the libraries need to match and it is very specific, compiling with not matching dependancies with the libraries will cause the segment faults you are experiencing , particularly with asset rpc requests I found with the ARM compiles I was doing for RavencoinOS. @underdarkskies might be able to provide some detail in regard to this.

Please try and recreate this with the binary releases, regarding the RPC queue. The best person to speak to is probably realbokito on ravencoin discord since he was playing around with it a lot. Our solution was to make requests one by one, and/or use a MySQL database to compare the global list before making the get assetdata requests.

I'll see if I can digup the config I had, but we recently had a brownout killing my bridgebox, so it might be a little while until I find it. In the meantime you can use the bitcoin rpc queueing reference as a guide, since ravencoin being a fork, it is essentially the same. I am not using MQ myself but I heard that some people were. Check in on the ravencoin discord in #development I'm certain more people would help you out if you have more questions!


Best,
Adam

**Comment by volbil** [comment]
@TronBlack yep, latest release have exactly the same issue
https://github.com/RavenProject/Ravencoin/releases/tag/v2.2.2

**Comment by volbil** [comment]
Ok, thanks to @ravenlandpush I figured out my issue. For some reason I used ```rpcworkquery``` instead of ```rpcworkqueue```. Afther setting this flag to 200 (just random picked number) now everything works like a charm.

Thanks everyone for help, I think this issue can be closed now :)

**Comment by volbil** [comment]
Ok, seams like it's still failing but less frequent :(

**Comment by ravenlandpush** [comment]
Hey its probably nothing , but just to check you have considered that you might be making too many parallel requests or running out of memory? I would advise against forking many RPC requests and run them sequentially, how many do you run at a time? I do not believe there is a significant performance gain running them parallel, but I could be wrong. I would run it with gdm debug, or strace -p -f pid to see if you can get an idea of what is going on when it happens. Important detail might include how debug.log behaves and what appears in it just before, in between and just after you see the issue you believe you are recreating. 

 I know its basic stuff, but as always pays dont forget to check dmesg and kernel.log for things, which you probably have already. Just in case it is OOM or something else causing the segs like security.limits like ASsize or something. What indexes do you have enabled? 

Best,
Adam

**Comment by volbil** [comment]
@ravenlandpush actually I forget to check memory consumption 😅 
Going to check it soon.

**Comment by ravenlandpush** [comment]
No worries it happens!! naturally because what could also cause the SEGV you see would be memory. Its interesting though what your seeing if it isnt;

I wonder if it could be a small bug with the way that the rpc queuing is defined in raven.conf, as, the person last I spoke to having such issues similar as you describe - was using such a configuration too (not everyone defines rpc queue).

It might just be a coincidental factor though, since anyone experiencing an segmentation fault when multi-querying rpc, might naturally dispose themselves to configuring queuing to try and alleviate it. Have you ever tried it without the queueing vars defined?  Or with very low or very large ranges for them? Something worth trying perhaps. Hope this you find out more about what your experiencing!

Best,
Adam

**Comment by volbil** [comment]
Hello everyone, I haven't managed to fix this issue on my own and node still crashing sometimes while fetching assets balances using `listassetbalancesbyaddress` but I figured workaround for it. If you enable address index it's possible to fetch address asset balances using `getaddressbalance` rpc call with `includeAssets` flag set to true. Maybe it would be useful for somebody :)

**Comment by hans-schmidt** [comment]
### I tried to duplicate this problem today for debugging purposes but was unable to duplicate it using the binary release linux64 versions 2.2.2.0 or 2.4.0.0 on ubuntu-18.04 

In a terminal window I ran=>
```
	/home/ubuntu-18p04/Desktop/Ravencoin/raven-2.4.0.0/bin/ravend -assetindex
```
After waiting for the server to initialize, in another terminal window I ran a bash script file which contained=>
```
	#! /bin/bash
	/home/ubuntu-18p04/Desktop/Ravencoin/raven-2.4.0.0/bin/raven-cli -rpcuser=xxx -rpcpassword=yyy listassetbalancesbyaddress RBB4oNXBuigYffe3x8FX7KXThU24h9jKv6 >> ./crash_test_out.txt &
		...
		same with 18 other addresses
		...
	/home/ubuntu-18p04/Desktop/Ravencoin/raven-2.4.0.0/bin/raven-cli -rpcuser=xxx -rpcpassword=yyy listassetbalancesbyaddress RBGtRiCKH8vQUdQ8sdNJFFNhE3dY1iATNA >> ./crash_test_out.txt &
```
I also tried v2.4.0.0 raven-qt with "-server' using the same version raven-cli
I also tried v2.2.2.0 ravend using the same version raven-cli	
I also tried v2.2.2.0 raven-qt with "-server' using the same version raven-cli

**Comment by volbil** [comment]
@hans-schmidt thanks for your reply, I will check everything one more time and report here.

**Comment by volbil** [comment]
Just builded node from latest commit and seams like this issue is gone now (at least I can't reproduce it with both `listassetbalancesbyaddress` and `getaddressbalance`). I think this issue should be closed now 👍
