### ISSUE TITLE
extra coins dissapear from show balance on transfer out of wallet.

### ISSUE THREAD

**Issue by MrsDelish** [RavenProject/Ravencoin#63]
### Describe the issue
There was a new report in #helpdesk  about some coins in  getting "lost"(17rvn) after a transfer was made out of the wallet. 
There was one transfer out + 17 coins in the last case.
Wallet shows wrong balance, it shows as lacking these 17 coins.
These coins were in a not shown address in the wallet.
with 'listaddressgroupings'  from console they coins can be seen.
Addressbook was used to send from.

Is this a known issue or working as intended.

This was reported in #helpdesk on Discord starting  April 10. 2018 18:11 CEST. 
and an older similar report April 4. 2018 17:55 CEST also in #helpdesk

### Machine specs:
- OS: Windows

**Comment by Karr** [comment]
I think I found the bug in the wallet.
I have the "enable coin control feature" enabled.  I have multiple address.  I select two addresses (when I have 3x or more) to send from and ANY left over fund is sent through the blockchain back to my wallet to a HIDDEN address.  The wallet is clueless of this in accounting and only console command: listaddressgroupings will see it.  I dump priv and import to use these funds.
Next send.. does same thing with a NEW address (hidden) created.  Continually.

I created new wallet and it reproduces.

**Comment by TronBlack** [comment]
Thank you for this feedback.   We will look into it.

**Comment by TronBlack** [comment]
We ran some tests, and it seems to be working as designed.  The send to an "internal" address (HD Derived change address) is "net settled" and you'll only see the fee accounted for in the transactions or on the QT Overview page.   We did not design this net settlement, but inherited from the bitcoin code fork.

If you find that you cannot spend those funds, or if I've missed something in your explanation that makes this worse than I'm describing, please let us know, and refer back to this issue.

Spends to internal addresses are net settled because it would be confusing to non-crypto people to see that they paid 10 Raven, and see another transaction (change) for 40 Raven that they did not plan for.   The change addresses are hidden to make it appear like a regular accounting transaction of (-10) instead of 50 input  10 (output)  40 (change output)
