### ISSUE TITLE
The version is not upgraded, what will be the problem?

### ISSUE THREAD

**Issue by debuggor** [RavenProject/Ravencoin#634]
my version is v2.2.2, and i do not want to upgraded v2.4.0. What will be the problem? thanks

**Comment by jeroz1** [comment]
2.4 contains bug fixes inherited from bitcoin.

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-June/017040.html

**Comment by debuggor** [comment]
@jeroz1  Does it affect the currency of the exchange?

**Comment by ravenlandpush** [comment]
the bug fixes in 2.4.0 were mainly to do with network consensus. It might be OK for you to continue running v2.2.2, provided there are enough nodes running the latest. 

That withstanding, it is not a guarantee. Of course, would recommend that you update. As it is always better to depend on ones own consensus, rather than the rest of the network. That said - its the global consensus which matters most.

Take that as what you will, it is certainly not advice to stay downgraded. But some affirmation that it 'might be' ok.

Best wishes,
Adam

**Comment by ravenlandpush** [comment]
I'm not able to find the CVE disclosure . Can someone else confirm whether @debuggor is at risk? Is this a network risk or individual nodeclient risk?
