### ISSUE TITLE
Warning: Unknown block versions being mined!

### ISSUE THREAD

**Issue by jessemarco** [RavenProject/Ravencoin#645]
I open wallet and I got warning:

Warning: Unknown block versions being mined! It's possible unknown rules are in effect

**Comment by lsji07** [comment]
Hi, I had the same issue briefly on my 2.5.1 wallet.

https://cdn.discordapp.com/attachments/429134613231697920/617299665603526666/unknown.png

Restart the wallet. This worked for my wallet.

https://cdn.discordapp.com/attachments/429134613231697920/617302143921160213/unknown.png

This appears to be a a gui issue only @blondfrogs

**Comment by ravenlandpush** [comment]
This is not a GUI issue, the error message is correct. There are some blocks that have a different version than expected, it is working as intended. I believe in this case it can be ignored since it relates to a patch that some pools are using which results in this error message.

(someone can correct me if i am mistaken!)

Best wishes,
adam

**Comment by blondfrogs** [comment]
Yes, this is only a GUI issue. There isn't any reason to be alarmed by this. We will be putting out a new release that will remove this now critical error from the GUI.

**Comment by jessemarco** [comment]
Thank you guys for super quick response.
