### ISSUE TITLE
GUI: Transactions view, width of columns and filtering.

### ISSUE THREAD

**Issue by fdoving** [RavenProject/Ravencoin#905]
Glitch in setting the width of columns when switching views.

#### If so, please list the steps to reproduce below:
1.  Open Transactions
2.  Select some transaction type without any transactions, I use "Asset Sent" 
3.  Switch view to Create Assets.
4.  Switch back to Transactions
5.  Select transaction type "Recieved with" or other type with transactions.
6.  The transaction-view looks messed up, hiding most of the information.

7.  Switch to Create Asset and back to Transactions to fix it.

Screenshot:
![RVN-transactions-view-glitch](https://user-images.githubusercontent.com/26197922/112349141-c6b48800-8cc8-11eb-87e3-b45ea77aaacf.png)

**Comment by MichaelFusco** [comment]
Was able to replicate with same results.

![Wallet Transactions Page Label Column Bunching Issue](https://user-images.githubusercontent.com/79958366/116032750-3c947200-a62e-11eb-96cc-7ee614e31937.png)


When switching away from an empty page and then returning, it may be defaulting to the column width settings it last used.

Suggest shifting the static column width of the Label column in the body to match the Label search box width of the heading bar. This may still leave the issue when switching from page to page when left last on an empty page.

Another option would be to make all column widths editable, but this still could open up issues with with changes due to standard movement around the QT.

![Wallet Transactions Page Column Alignment](https://user-images.githubusercontent.com/79958366/116031807-75cbe280-a62c-11eb-89b8-0a18c6a163c7.png)
